### ISSUE TITLE
Support having externals dependencies

### ISSUE THREAD

**Issue by HugoImaios** [lhapaipai/vite-plugin-symfony#36]
### Description

Currently, from what I understand, this plugin does not support having externals dependencies in build mode.
I did set `build.rollupOptions.external`, `build.rollupOptions.out.globals` (which replaces the previous one with what I need) and just in case also `optimizeDeps.exclude`.
But the plugin is still throwing me this error :
```[symfony-entrypoints] Unable to find my-external-dep```
where `my-external-dep` is one of the external dep I mentionned earlier

**Comment by HugoImaios** [comment]
complete error log
```
[symfony-entrypoints] Unable to find my-external-dep
✓ built in 26.99s
error during build:
Error: Unable to find my-external-dep
    at resolveEntrypoint (file:///var/www/node_modules/vite-plugin-symfony/dist/index.mjs:271:15)
    at getBuildEntryPoints (file:///var/www/node_modules/vite-plugin-symfony/dist/index.mjs:242:30)
    at Object.generateBundle (file:///var/www/node_modules/vite-plugin-symfony/dist/index.mjs:577:29)
    at file:///var/www/node_modules/rollup/dist/es/shared/node-entry.js:18606:40
```

**Comment by lhapaipai** [comment]
Hi @HugoImaios, thank you for your feedback. Indeed there is something that does not adopt the expected behavior but I'm missing a bit of context.

can you give me an example of your issue with
- the html or twig code which carries out the external imports (by indicating to me the attributes of the script tags)
- and also the way in which you carried out your imports. (`type="module"` or not, bare import or relative import, etc...)

here is what i just tried and i would like another angle of view to see how to change the code

global config for examples
```js
// vite.config.js
import { defineConfig } from 'vite'
import { dirname, resolve } from 'path';

import symfonyPlugin from 'vite-plugin-symfony';

export default defineConfig({
  plugins: [
    symfonyPlugin(),
  ],

  build: {
    rollupOptions: {
      input: {
        "app": "./assets/app.js",
      },
      external: ['./external-file.js', 'leaflet'],
    },
  },
});
```

## example 1
```html
<script defer src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
crossorigin=""></script>

{% block stylesheets %}
{{ vite_entry_link_tags('app') }}
{% endblock %}

```js
// app.js
// it's ok if you do nothing...
console.log('welcome leaflet', L)
```
```js
// ./public/build/assets/app-XXX.js
// build file is unchanged
console.log('welcome leaflet', L)
```

## example 2

but with this
```diff
// vite.config.js
export default {
  build: {
    rollupOptions: {
+      external: ['./external-file.js']
    }
  }
};
```
```js
// app.js
import ext from "external-file"
console.log('welcome my-file', ext);
```
it crash with vite-plugin-symfony
if plugin removed it produce this but the browser won't understand it
```js
// ./public/build/assets/app-XXX.js
import ext from "external-file";
console.log("welcome my-file", ext);
```
and I admit that the rollup option `build.rollupOptions.output.globals` seemed very very obscure to me.
have a good evening !!

**Comment by lhapaipai** [comment]
fixed https://github.com/lhapaipai/symfony-vite-dev/commit/723972c844b9565b00f8ae0f572fdd02f31c2bb7
if you have external dependencies you need to define them in your `vite.config.js` in the  `external` property.

```js
// vite.config.js
export default {
  build: {
    rollupOptions: {
      external: ['my-external-dep']
    }
  }
}
```
